using Microsoft.EntityFrameworkCore.Migrations;

namespace TechYouKnow.Migrations
{
    public partial class SeedDatabaseForCategoriesAndPost : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("INSERT INTO BLOGCATEGORIES (TITLE) VALUES ('CATEGORY 1')");
            migrationBuilder.Sql("INSERT INTO BLOGCATEGORIES (TITLE) VALUES ('CATEGORY 2')");
            migrationBuilder.Sql("INSERT INTO BLOGCATEGORIES (TITLE) VALUES ('CATEGORY 3')");
            migrationBuilder.Sql("INSERT INTO BLOGCATEGORIES (TITLE) VALUES ('CATEGORY 4')");
            migrationBuilder.Sql("INSERT INTO BLOGCATEGORIES (TITLE) VALUES ('CATEGORY 5')");
            migrationBuilder.Sql("INSERT INTO BLOGCATEGORIES (TITLE) VALUES ('CATEGORY 6')");

            migrationBuilder.Sql("INSERT INTO BLOGPOSTS (TITLE, INTRO, CONTENT) VALUES ('Blog BECode Title 1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum')");
            migrationBuilder.Sql("INSERT INTO BLOGPOSTS (TITLE, INTRO, CONTENT) VALUES ('Blog BECode Title 2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum')");
            migrationBuilder.Sql("INSERT INTO BLOGPOSTS (TITLE, INTRO, CONTENT) VALUES ('Blog BECode Title 3', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum')");
            migrationBuilder.Sql("INSERT INTO BLOGPOSTS (TITLE, INTRO, CONTENT) VALUES ('Blog BECode Title 4', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum')");
            migrationBuilder.Sql("INSERT INTO BLOGPOSTS (TITLE, INTRO, CONTENT) VALUES ('Blog BECode Title 5', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum')");
            migrationBuilder.Sql("INSERT INTO BLOGPOSTS (TITLE, INTRO, CONTENT) VALUES ('Blog BECode Title 6', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent elementum, ex vitae vulputate convallis, ipsum tellus semper tellus, eu lacinia erat ipsum ac nulla.Donec sit amet turpis a mi semper venenatis.Etiam bibendum')");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DELETE FROM BLOGPOSTS");
            migrationBuilder.Sql("DELETE FROM BLOGCATEGORIES");
        }
    }
}
